:blc_ms_version: 0.11.0-SNAPSHOT
:toc:
:icons: font
:source-highlighter: prettify
:project_id: ms-tutorials
:sectnums:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Microservice Tutorials

== Project Structure

.Project Modules Overview
|===
|Module |Description

A basic project that runs Broadleaf's unified microservices admin with the `Catalog`
microservice and other necessary supporting services.

|`ms-tutorial-base`
| Intended to be the initial project structure on which the other tutorials are based

|`ms-tutorial-extension-complete`
| A completed tutorial that showcases typical extensions and customizations on top of the base project

|`ms-tutorial-new-entity-complete`
| A completed tutorial that showcases the creation of new domain, repositories, services, and endpoints
on top of Broadleaf's `Catalog` microservice

|===

== What Do I Need?
In order to get this reference project running locally, you will want to obtain and install
the following:

=== Credentials
Access to Broadleaf's Docker Registry and Maven Nexus is needed in order to pull down the
appropriate resources.

Once you have obtained these credentials, you will need to configure them for the dependencies
below.

[NOTE]
====
Contact `info@broadleafcommerce.com` for information on how to receive these credentials
====

=== Java
You will need Java 8 or 11 installed on your machine.

* https://openjdk.java.net/projects/jdk/11/[Open JDK]
* https://www.oracle.com/java/technologies/javase-jdk11-downloads.html[Oracle JDK]

=== Docker
You will need to have https://docs.docker.com/install/[Docker Engine & Docker Compose] installed
locally

[TIP]
====
Docker Desktop for both Mac and Windows already includes compose along with other
docker apps.
====

Once you have Docker installed, you will want to authenticate with Broadleaf's Docker registry.

Type the following into your CLI:

[source,shell script]
----
docker login repository.broadleafcommerce.com:5001
----

When prompted, type in the username and password you received above.

[IMPORTANT]
====
You'll also want to configure Docker settings to use appropriate resources.
A good rule of thumb is to allow Docker to consume around 3/4 of your system resources
as necessary.

At a minimum, you will want to allocate at least 2 CPUs and 4-6 GB Memory

Ideally for a developer machine, you will want to allocate something like:
6 CPUs, 8 GB Memory, 4 GB Swap.
====

=== Maven
You'll need to have Maven installed locally as well.
https://maven.apache.org/download.cgi[Maven 3.5 or later] is recommended.

Once you have Maven installed, another step you need to do before you can
build the project is to configure the authentication. Maven requires it to be specified in a
file called `settings.xml` that has to be in the `.m2` subdirectory in a user’s home directory.

If you already have Maven locally, then add the following server to your `<servers> list in your `settings.xml`:
[source,xml]
----
<server>
  <id>broadleaf-microservices</id>
  <username>username_here</username>
  <password>password_here</password>
</server>
----

If you do not already have an `.m2` subdirectory and a `settings.xml` file within it, then follow these steps:
1. Create a folder called `.m2` in your home directory
2. Create a file called `settings.xml` in the `.m2` folder
3. Copy the following contents to your `~/.m2/settings.xml` making sure to
replace the credentials with the ones you received above:

[source,xml]
----
<settings xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.1.0 http://maven.apache.org/xsd/settings-1.1.0.xsd"
    xmlns="http://maven.apache.org/SETTINGS/1.1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <servers>
    <server>
      <id>broadleaf-microservices</id>
      <username>username_here</username>
      <password>password_here</password>
    </server>
  </servers>
</settings>
----

[TIP]
====
More info about authenticating with private repositories can be found
https://maven.apache.org/settings.html#Servers[here] and
https://maven.apache.org/ref/3.6.3/maven-settings/settings.html[here]
====

== Running the Project

1. From the root directory of MicroservicesTutorial, run the following:
+
[source,shell script]
----
mvn clean install
----
+
2. Before you start up all the APIs, you'll need to first start up a few supporting services.
These are provided via Docker images and started from the command line by navigating to one
of the sample tutorial directories (`ms-tutorial-base`, `ms-tutorial-extension-complete`,
or `ms-tutorial-new-entity-complete`) of this project and running:
+
[source,shell script]
----
docker-compose up -d
----
+
3. Next, you will want to start up the core backend commerce APIs by running the following command inside teh same tutorial directory:
+
[source,shell script]
----
mvn spring-boot:run
----
+
4. Once the Spring Boot application has started, you can visit the administration console from a browser:
+
- Admin Console: https://localhost:8446
* Username: `master@test.com`
* Password: `Pass1word!`