broadleaf:
  database:
    provider: jpa
  composite:
    datasource:
      url: 'jdbc:postgresql://localhost:5432/broadleaf'
      username: broadleaf
      password: demo
      hikari:
        maximumPoolSize: 10
      properties:
        hibernate:
          jdbc:
            lob:
              non_contextual_creation: true
  adminnavigation:
    liquibase:
      change-log: 'classpath:/db/changelog/adminnavigation.tutorialdata.postgresql.changelog-master.yaml'
      liquibase-schema: public
      default-schema: adminnavigation
    delegating:
      schema: adminnavigation
      delegate-ref: composite
  adminuser:
    liquibase:
      change-log: 'classpath:/db/changelog/adminuser.tutorialdata.postgresql.changelog-master.yaml'
      liquibase-schema: public
      default-schema: adminuser
    delegating:
      schema: adminuser
      delegate-ref: composite
  asset:
    internal:
      content-provider-url-prefix: 'https://localhost:8447/'
      prepend-request-context-path: false
    provider:
      contentUrlPrefix: 'https://localhost:8447/content'
    liquibase:
      change-log: 'classpath:/db/changelog/asset.tutorialdata.postgresql.changelog-master.yaml'
      liquibase-schema: public
      default-schema: asset
    delegating:
      schema: asset
      delegate-ref: composite
  catalog:
    liquibase:
      change-log: 'classpath:/db/changelog/catalog.tutorialdata.postgresql.changelog-master.yaml'
      liquibase-schema: public
      default-schema: catalog
    delegating:
      schema: catalog
      delegate-ref: composite
  common:
    data:
      route:
        enabled: true
    policy:
      validation:
        enforce: true
    ssl-verification:
      disabled: true
  image:
    availableEffects: 'crop, resize, scale, thumbnail, unsharp'
  metadata:
    liquibase:
      change-log: 'classpath:/db/changelog/metadata.tutorialdata.postgresql.changelog-master.yaml'
      liquibase-schema: public
      default-schema: metadata
    delegating:
      schema: metadata
      delegate-ref: composite
  modelmapper:
    cache:
      load:
        enabled: true
  resource:
    security:
      oauth2:
        defaultAllowAllAnonymous: false
  sandbox:
    liquibase:
      change-log: 'classpath:/db/changelog/sandbox.tutorialdata.postgresql.changelog-master.yaml'
      liquibase-schema: public
      default-schema: sandbox
    preview:
      encoder:
        # Generated using KeyGeneratorUtil at 2048-bit strength
        encoded-private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCMQ9Xq3UWtXkMj2M2z9f0Za/HhaBWMpycZ4eRTGAKQH9kMYLm0CiUG/Jm2GKdrGZKBYqI8mXUxK979qCvQuR+xdaAvK02KzyMUWlu9b6ALhrVw3Er/aiZhkxhQE/MIYoW3RBVFt9yuAJqaKJuFEFFSYjLmt2GlfcBt6L1lRcLignfm26Bu7nLhCFC29Y59fIlfe6RpJvok7ppTOvvRCUzODbVNWjeDjQ3jvpra56zJcPW9KNxQggBPVKjuGbR9AOyTsWt3Pt4BvBjdNmieVluz27BoVdMGcju/nEdRhwbikQFp0qeWi0utZbfgM4QdR2XC5rc+7ras/aMkTCtoJmS1AgMBAAECggEAYhOYw3XfH592sN0K0JfjVuA8rFD8KHJEi/uAjH2QZThvqxEDKJmjVGRSEprgjam+4EuYh2kCIdS8Qn9Ry8t2Fr7Zt8G+oZ2+uJ+J4EbqEMUrn3PZ2QhfOAEDkhKw8B77wq6PdUVfwCdZ8wsL25oSUtmpH9wAIhhw8ik4LVT/NSPbTiOaGRPdQE31DCnwLG8chDpkX2VkhQp0ah4+1NwQHyGLkrPY9P6tpcsxCpDK9OcIC8eJW612dMUpTLr1AGvAiuCO/Bhzr1d7HCwBOm95PhJWRi+zLOmWz2K9QWxvqwOsGiNb/23ngFu03tsAGz8yGdKFMRpG0ywLPykZmnEw7QKBgQDbry8lcIRlYSigcPZWo2AHLCOZGxmi9O9dXE/MB5d+Qw4HalHbVxnykwRF0uWobQf99JNSeFqkZy51dGvr55ADaJYuA1Hvr+Yqu63aS2iLbMk+xmBpfLRAmuuCcC0v+WbsNjYz0hdNHf08/sumjM6QoGOGF2PWfddtwJo0847nXwKBgQCjc7Tb3AHlkQR6pfHUwz/7oynI6p0/nw/Q9UXIYXhCYJlrqddz0QMn5LhOILTjJq9dAX7vUNhIIpBBFaVk5voagpnkRbkUG5LHPtm/Wps/Uosdg6WHgB4xWVcE0nWJZWCtwgv60N9T3qU8t3lyQg8BkFyBcJJg9gL2D2BrF6JQawKBgQDCKxurpsCOboqfDFjeiLZGgJ/SIl7NZlnulbm95vPiWFgc+77v9BNuEL1VDauI6x2GO9a+rLvI1Z39mHIO5vOl35nlf2+7Pyhbmth1ufLkULmq72GluuACvirsdkOqRHDQ1LWhpc6MjbYXZEkRoyCsOebdTO0kVsPDMNnbdW5YVwKBgH+K8y64T1aWQVt/D+SI8u1llV5tDIUvlkTkjy5cOF37SNxFLJT4HLFNfS+hv+ScNCyr1SPi/tHS/qN6w5On1LNJA9KnQVNabL9C4OC7T/cqbtl593lzVJwHbaqamxK6Y6VSjMyLniiwzFlDheXNfC4pOrXaZK56aTceKouGZqa/AoGAbPkdybZD/NyJxcQm3sE+ff6v9iHxzhg4aULGWhGeJd38Iq3rSJBo4gCt3Zj7Psq+Jt9s+BY4GbT/5MbfWG2dC1mbexkbdz/cH+ytg55ihD0TJVhGCHz/5o+eYkP26nDIAvnbWcGRA5Vzxg2XB9g/OoPPNhakmhLQXDILu7OJY0k=
      decoder:
        encoded-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjEPV6t1FrV5DI9jNs/X9GWvx4WgVjKcnGeHkUxgCkB/ZDGC5tAolBvyZthinaxmSgWKiPJl1MSve/agr0LkfsXWgLytNis8jFFpbvW+gC4a1cNxK/2omYZMYUBPzCGKFt0QVRbfcrgCamiibhRBRUmIy5rdhpX3Abei9ZUXC4oJ35tugbu5y4QhQtvWOfXyJX3ukaSb6JO6aUzr70QlMzg21TVo3g40N476a2uesyXD1vSjcUIIAT1So7hm0fQDsk7Frdz7eAbwY3TZonlZbs9uwaFXTBnI7v5xHUYcG4pEBadKnlotLrWW34DOEHUdlwua3Pu62rP2jJEwraCZktQIDAQAB
    delegating:
      schema: sandbox
      delegate-ref: composite
  scheduledjob:
    liquibase:
      change-log: 'classpath:/db/changelog/scheduledjob.tutorialdata.postgresql.changelog-master.yaml'
      liquibase-schema: public
      default-schema: scheduledjob
    delegating:
      schema: scheduledjob
      delegate-ref: composite
  tenant:
    liquibase:
      change-log: 'classpath:/db/changelog/tenant.tutorialdata.postgresql.changelog-master.yaml'
      liquibase-schema: public
      default-schema: tenant
    delegating:
      schema: tenant
      delegate-ref: composite
    global:
      allowed-locales:
        - en_US
    urlresolver:
      admin:
        port: 8446
  bulk:
    processBulkUpdateRequest:
      retry:
        retryClusterServiceNamespace: process-bulkupdate-request-flexpackage
    createSandboxRequest:
      retry:
        retryClusterServiceNamespace: create-sandbox-request-bulk-flexpackage
    deleteSandboxRequest:
      retry:
        retryClusterServiceNamespace: delete-sandbox-request-bulk-flexpackage
  changesummary:
    retry:
      retryClusterServiceNamespace: changesummary-flexpackage
  export:
    process-export-request:
      retry:
        retryClusterServiceNamespace: process-export-request-flexpackage
  import:
    createSandboxRequest:
      retry:
        retryClusterServiceNamespace: create-sandbox-request-import-flexpackage
  persistence:
    retry:
      retryClusterServiceNamespace: persistence-flexpackage
  single-index-request:
    retry:
      retryClusterServiceNamespace: single-index-request-flexpackage
  transitionrequestcompletion:
    retry:
      retryClusterServiceNamespace: completion-flexpackage
  transition:
    retry:
      retryClusterServiceNamespace: transition-flexpackage
  scheduledjobtrigger:
    retry:
      retryClusterServiceNamespace: trigger-flexpackage
server:
  port: 8447
  servlet:
    context-path: /
  ssl:
    key-store: 'classpath:local.keystore'
    key-store-password: storepass
spring:
  cache:
    type: none
  integration:
    jdbc:
      initialize-schema: always
  cloud:
    stream:
      bindings:
        persistenceInputTenantSyncDataTracking:
          group: flexpackage-tenant-sync
          destination: persistence
        promotionInput:
          group: flexpackage-promotion
          destination: promotion
        deploymentInput:
          group: flexpackage-deployment
          destination: deployment
        rejectionInput:
          group: flexpackage-rejection
          destination: rejection
        reversionInput:
          group: flexpackage-reversion
          destination: reversion
        rebasingInput:
          group: flexpackage-rebase
          destination: rebasing
        processBulkUpdateRequestInput:
          group: flexpackage-bulk-update
          destination: bulkUpdateRequest
        batchRequestInput:
          group: flexpackage-batch
          destination: batchRequest
        triggeredJobEventInputOrphanBulk:
          group: flexpackage-orphan-bulk
          destination: triggeredJobEvent
        triggeredJobEventInputOrphanExport:
          group: flexpackage-orphan-export
          destination: triggeredJobEvent
        processExportRequestInput:
          group: flexpackage-export
          destination: exportRequest
        triggeredJobEventInputPurgeLock:
          group: flexpackage-purge-lock
          destination: triggeredJobEvent
        triggeredJobEventInputPruneNotification:
          group: flexpackage-prune-notification
          destination: triggeredJobEvent
        triggeredJobEventInputPurgeSandbox:
          group: flexpackage-purge-sandbox
          destination: triggeredJobEvent
      kafka:
        default:
          consumer:
            configuration:
              max:
                poll:
                  interval:
                    ms: 1200000
    bus:
      enabled: false
  datasource:
    initialization-mode: never
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: true
        dialect: com.broadleafcommerce.data.tracking.jpa.hibernate.PostgresDialect
  messages:
    useCodeAsDefaultMessage: true
  security:
    oauth2:
      client:
        provider:
          catalog:
            token-uri: 'https://localhost:8443/oauth/token'
        registration:
          catalog:
            authorization-grant-type: client_credentials
            client-id: catalog
            client-secret: catalog_secret
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      resolve-lazily: true
  thymeleaf:
    cache: false
logging:
  level:
    org:
      apache:
        kafka: WARN